# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IzzyFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_name', models.CharField(max_length=250)),
                ('flavor_description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('date_seen', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
    ]
