# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='izzyflavor',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
