# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoops', '0003_auto_20160227_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izzyflavor',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='izzyflavor',
            name='favorited_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, null=True, size=None),
        ),
    ]
