# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoops', '0004_auto_20160228_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='izzyflavor',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='favoriteflavor',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoops.IzzyFlavor'),
        ),
        migrations.AddField(
            model_name='favoriteflavor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
