# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoops', '0005_auto_20160228_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=250)),
                ('flavor_rating', models.CharField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars')], max_length=1)),
                ('review_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoops.IzzyFlavor')),
            ],
        ),
    ]
