# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoops', '0007_auto_20160229_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorreview',
            name='flavor_rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars')]),
        ),
    ]
